version: '3'

services:
  web:
    image: nginx
    volumes:
      - ./html:/usr/share/nginx/html/
      - ./site.conf:/etc/nginx/conf.d/default.conf
    networks:
      - default
    ports:
      - 7000:80

  php:
    image: murilogp/php-7.4
    volumes:
      - ./html:/usr/share/nginx/html/
      - ./php.ini:/usr/local/etc/php/php.ini
    networks:
      - default